package music.business;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.text.NumberFormat;
import java.util.Locale;

public class ProductTest {

    @Test
    public void testProductGettersAndSetters() {
        Product product = new Product();
        product.setCode("P001");
        product.setDescription("Test Product");
        product.setPrice(19.99);

        assertEquals("P001", product.getCode());
        assertEquals("Test Product", product.getDescription());
        assertEquals(19.99, product.getPrice());
    }

    @Test
    public void testPriceCurrencyFormat() {
        Product product = new Product();
        product.setPrice(19.99);
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(Locale.US);
        String expectedFormat = currencyFormat.format(19.99);
        assertEquals(expectedFormat, product.getPriceCurrencyFormat());
    }

    @Test
    public void testProductIdAutoGenerated() {
        Product product = new Product();
        assertNull(product.getId(), "Product ID should initially be null until persisted");
    }
}
